# 네이버 카페 URL
NAVER_CAFE_REACTION_MEMBERKEY = "X4X7z5aOcioCbe1qI-E8UVLKwmBlKET9fovk6zfnmPY"
NAVER_CAFE_ARTICLE_API = "https://apis.naver.com/cafe-web/cafe2/ArticleListV2dot1.json"
NAVER_CAFE_CLUBID = 27842958
NAVER_CAFE_MENUID = 367
